#! /bin/sh

$HOME/.config/bspwm/bin/bspstart.sh

alias bc='bspc config'
alias br='bspc rule -a'

bspc monitor eDP1 -d I II III IV V
bspc monitor HDMI1 -d VI VII VII IX X

bc remove_disabled_monitors  true
bc remove_unplugged_monitors true

bc border_width              0
bc window_gap                5
bc split_ratio               0.5
bc borderless_monocle        true
bc gapless_monocle           true
bc single_monocle            true
bc focus_follows_pointer     true

br alacritty-float focus=on state=floating
br feh             focus=on state=floating
br Viewnior        focus=on state=floating

br Alacritty       desktop='^1' follow=on focus=on
br Sublime_text    desktop='^2' follow=on focus=on
br Sublime_merge   desktop='^2' follow=on focus=on
br Chromium        desktop='^3' follow=on focus=on
br Dynalist        desktop='^4' follow=on focus=on
br obsidian        desktop='^4' follow=on focus=on
br SiYuan          desktop='^4' follow=on focus=on
br Gimp-2.10       desktop='^5' follow=on focus=on
br Pcmanfm         desktop='^5' follow=on focus=on
br Lxappearance    desktop='^5' follow=on focus=on
br Pavucontrol     desktop='^5' follow=on focus=on
br Arandr          desktop='^5' follow=on focus=on
